.TH "42sh" "1" "October 30, 2018" "42sh 1\&.0"
.SH "NAME"
42sh \- The return of the Vengeance from the past
.SH "OVERVIEW"
.PP
.PD 0
There are many other shells, such as bash, csh, tcsh, ksh, ash, etc\&.
.TP
These are inferior builds\&. \fB42sh\fP will crush them all\&.
.PP
.PD 0
.TP
.TP
\fIsh\fP           \fB42sh\fP would rm -rf sh and throw it out to sea\&.
.TP
\fIbash\fP         \fB42sh\fP should be called bazsh\&.
.TP
\fIcsh\fP          \fB42sh\fP doesn't care about csh\&.
.TP
\fItcsh\fP         \fBt42sh\fP will never be necessary\&.
.TP
\fIzsh\fP          \fB42sh\fP would win zsh in an arm wrestle\&.
.PD
.SH "DESCRIPTION"
\fB42sh\fP is a UNIX command interpreter (shell) usable as an interactive
login shell\&.  Of the standard shells, \fB42sh\fP
most closely resembles \fBzsh\fP but includes many enhancements\&.
.\" Yodl file: Zsh/metafaq.yo
.SH "AUTHOR(S)"
\fB42sh\fP has been said to have been written by aliens with extraordinary
abilities\&.  It is said that they cannot segfault, bus error, double free,
infinite loop, feature twisted logic or leak even if they try\&.
.SH "INVOCATION"
\&./42sh
.SH "USER GUIDE"
run \fIhelp\fP inside \fB42sh\fP
.SH "SEE ALSO"
\fIsh\fP(1),
\fIcsh\fP(1),
\fItcsh\fP(1),
\fIrc\fP(1),
\fIbash\fP(1),
\fIksh\fP(1),
\fIzshbuiltins\fP(1),
\fIzshcompwid\fP(1),
\fIzshcompsys\fP(1),
\fIzshcompctl\fP(1),
\fIzshexpn\fP(1),
\fIzshmisc\fP(1),
\fIzshmodules\fP(1),
\fIzshoptions\fP(1),
\fIzshparam\fP(1),
\fIzshzle\fP(1)
.PP
\fBIEEE Standard for information Technology \-
Portable Operating System Interface (POSIX) \-
Part 2: Shell and Utilities\fP,
IEEE Inc, 1993, ISBN 1\-55937\-255\-9\&.
